import { ArrowLeftOutlined, CalendarOutlined, ClockCircleOutlined, DownOutlined, FolderOpenOutlined, MenuOutlined, PlusOutlined, ReloadOutlined, SearchOutlined, SendOutlined, StopOutlined } from '@ant-design/icons'
import { Alert, Badge, Button, Collapse, Drawer, Empty, Form, Input, List, Modal, Radio, Segmented, Select, Space, Spin, Tag, Typography } from 'antd'
import { useCallback, useEffect, useMemo, useRef, useState } from 'react'
import { useNavigate, useSearchParams } from 'react-router-dom'

import { cancelSchedule, createSchedule, createSession, fetchExperiments, fetchProjects, fetchSchedules, fetchSessions, fetchTranscript, interruptSession, sendMessage, type CodexSchedule, type CodexSession, type Experiment, type ProjectCandidate, type TranscriptTurn } from '../api/features'

type ArchiveFilter = 'false' | 'true' | 'all'
type Delivery = 'at_time' | 'experiment_succeeded'

function stateColor(state: CodexSession['state']) {
  if (state === 'running') return '#22C7A9'
  if (state === 'failed' || state === 'orphaned') return '#ff7875'
  if (state === 'queued' || state === 'creating') return '#faad14'
  return '#7f8c99'
}

function Transcript({ turns, live }: { turns: TranscriptTurn[]; live: string }) {
  if (turns.length === 0 && !live) return <Empty className="codex-empty" description="这个会话还没有可显示的对话" />
  return <div className="codex-transcript" aria-live="polite">
    {turns.flatMap((turn) => turn.items.map((item) => {
      if (item.kind === 'command_summary' || item.kind === 'file_change_summary') return <Collapse key={item.item_id} ghost size="small" className="execution-summary" items={[{ key: 'summary', label: item.kind === 'command_summary' ? '命令执行摘要' : '文件变更摘要', children: <pre>{item.text}</pre> }]} />
      const role = item.kind === 'user_message' ? 'user' : item.kind === 'error' ? 'error' : 'assistant'
      return <article key={item.item_id} className={`codex-message ${role}`}><div className="message-role">{role === 'user' ? '你' : role === 'error' ? '错误' : 'Codex'}</div><div className="message-body">{item.text}</div></article>
    }))}
    {live && <article className="codex-message assistant streaming"><div className="message-role">Codex</div><div className="message-body">{live}<span className="stream-caret" /></div></article>}
  </div>
}

export function CodexPage({ csrf }: { csrf: string }) {
  const navigate = useNavigate(); const [searchParams] = useSearchParams(); const targetSession = searchParams.get('session')
  const [sessions, setSessions] = useState<CodexSession[]>([]); const [selectedId, setSelectedId] = useState<string | undefined>(targetSession ?? undefined)
  const [archiveFilter, setArchiveFilter] = useState<ArchiveFilter>('false'); const [query, setQuery] = useState(''); const [railOpen, setRailOpen] = useState(false); const [railCollapsed, setRailCollapsed] = useState(false)
  const [creating, setCreating] = useState(false); const [scheduling, setScheduling] = useState(false); const [scheduleListOpen, setScheduleListOpen] = useState(false)
  const [projects, setProjects] = useState<ProjectCandidate[]>([]); const [experiments, setExperiments] = useState<Experiment[]>([]); const [schedules, setSchedules] = useState<CodexSchedule[]>([])
  const [turns, setTurns] = useState<TranscriptTurn[]>([]); const [cursor, setCursor] = useState<string>(); const [historyLoading, setHistoryLoading] = useState(false); const [live, setLive] = useState('')
  const [prompt, setPrompt] = useState(''); const [error, setError] = useState<string>(); const [sending, setSending] = useState(false); const requestGeneration = useRef(0)

  const loadSessions = useCallback(async () => { try { const items = await fetchSessions(undefined, archiveFilter); setSessions(items); setSelectedId((current) => items.some((item) => item.session_id === current) ? current : items[0]?.session_id) } catch (reason) { setError(reason instanceof Error ? reason.message : 'Codex 会话不可用') } }, [archiveFilter])
  // Initial remote synchronization; state updates happen after the requests settle.
  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(() => { void loadSessions(); void fetchProjects().then(setProjects); void fetchExperiments().then(setExperiments) }, [loadSessions])
  const selected = sessions.find((item) => item.session_id === selectedId)

  const loadHistory = useCallback(async (older = false) => {
    if (!selectedId) return; const generation = older ? requestGeneration.current : ++requestGeneration.current; setHistoryLoading(true)
    try { const page = await fetchTranscript(selectedId, older ? cursor : undefined); if (generation !== requestGeneration.current) return; const chronological = [...page.turns].reverse(); setTurns((current) => older ? [...chronological, ...current.filter((turn) => !chronological.some((old) => old.turn_id === turn.turn_id))] : chronological); setCursor(page.next_cursor); if (!older) setLive('') }
    catch (reason) { if (generation === requestGeneration.current) setError(reason instanceof Error ? reason.message : '无法读取对话历史') }
    finally { if (generation === requestGeneration.current) setHistoryLoading(false) }
  }, [cursor, selectedId])

  // Reset transient presentation state when the selected remote thread changes.
  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(() => { setTurns([]); setCursor(undefined); setLive(''); if (selectedId) void loadHistory(false) }, [selectedId]) // eslint-disable-line react-hooks/exhaustive-deps
  useEffect(() => { if (selectedId) void fetchSchedules(selectedId).then(setSchedules) }, [selectedId])
  useEffect(() => {
    const stream = new EventSource('/api/v1/events/stream'); stream.addEventListener('codex.session.updated', () => void loadSessions()); stream.addEventListener('codex.schedule.updated', () => { if (selectedId) void fetchSchedules(selectedId).then(setSchedules) }); stream.addEventListener('codex.turn.completed', () => { void loadSessions(); void loadHistory(false) }); stream.addEventListener('codex.stream.resync', () => void loadHistory(false))
    stream.addEventListener('codex.message.delta', (event) => { try { const envelope = JSON.parse((event as MessageEvent<string>).data) as { payload?: { session_id?: string; data?: { delta?: string } } }; const delta = envelope.payload?.data?.delta; if (envelope.payload?.session_id === selectedId && delta) setLive((value) => value + delta) } catch { /* history reload is recovery */ } })
    return () => stream.close()
  }, [loadHistory, loadSessions, selectedId])

  const grouped = useMemo(() => { const filtered = sessions.filter((item) => `${item.title ?? ''} ${item.project_id}`.toLowerCase().includes(query.toLowerCase())); return Object.entries(filtered.reduce<Record<string, CodexSession[]>>((groups, item) => { (groups[item.project_id] ??= []).push(item); return groups }, {})) }, [query, sessions])
  const send = async () => { if (!selected || !prompt.trim()) return; const text = prompt.trim(); setPrompt(''); setSending(true); const optimistic = `optimistic-${Date.now()}`; setTurns((current) => [...current, { turn_id: optimistic, status: 'queued', items: [{ item_id: optimistic, kind: 'user_message', text }] }]); try { await sendMessage(csrf, selected.session_id, text, 'queue'); await loadSessions() } catch (reason) { setPrompt(text); setError(reason instanceof Error ? reason.message : '发送失败') } finally { setSending(false) } }

  const rail = <aside className="codex-rail" aria-label="项目和会话"><div className="codex-rail-head"><Button type="text" icon={<ArrowLeftOutlined />} onClick={() => navigate('/')} aria-label="返回控制台" /><Typography.Title level={4}>Codex</Typography.Title><Button type="text" icon={<PlusOutlined />} onClick={() => setCreating(true)} aria-label="新建会话" /></div><Input allowClear prefix={<SearchOutlined />} placeholder="搜索项目或会话" value={query} onChange={(event) => setQuery(event.target.value)} /><Segmented block value={archiveFilter} onChange={(value) => setArchiveFilter(value as ArchiveFilter)} options={[{ label: '当前', value: 'false' }, { label: '归档', value: 'true' }, { label: '全部', value: 'all' }]} /><div className="codex-session-groups">{grouped.map(([project, items]) => <section key={project} className="session-group"><div className="session-group-title"><FolderOpenOutlined /><span>{project}</span></div><List dataSource={items} renderItem={(item) => <List.Item className={selectedId === item.session_id ? 'session-row selected' : 'session-row'} onClick={() => { setSelectedId(item.session_id); setRailOpen(false) }}><div className="session-copy"><span>{item.title || '未命名会话'}</span><small>{item.mode} · {item.state}</small></div><Badge color={stateColor(item.state)} /></List.Item>} /></section>)}</div></aside>

  return <main className={`codex-workspace ${railCollapsed ? 'rail-collapsed' : ''}`}><div className="codex-desktop-rail">{rail}</div><Drawer className="codex-mobile-drawer" placement="left" open={railOpen} onClose={() => setRailOpen(false)} width={Math.min(320, window.innerWidth - 32)} closable={false}>{rail}</Drawer><section className="codex-conversation"><header className="conversation-head"><Space><Button className="mobile-only" type="text" icon={<MenuOutlined />} onClick={() => setRailOpen(true)} aria-label="打开会话列表" /><Button className="desktop-only" type="text" icon={railCollapsed ? <MenuOutlined /> : <ArrowLeftOutlined />} onClick={() => setRailCollapsed((value) => !value)} aria-label="折叠会话列表" /><div><Typography.Text strong>{selected ? selected.title || selected.session_id : '选择一个会话'}</Typography.Text><div className="conversation-meta">{selected ? `${selected.project_id} · ${selected.agent_id} · ${selected.mode}` : 'FarHelm Codex workspace'}</div></div></Space><Space><Button icon={<CalendarOutlined />} onClick={() => setScheduleListOpen(true)}>定时任务</Button><Button icon={<ReloadOutlined />} onClick={() => void loadHistory(false)} aria-label="刷新对话" /></Space></header>{error && <Alert className="codex-alert" showIcon closable type="warning" title="Codex 操作失败" description={error} onClose={() => setError(undefined)} />}<div className="conversation-scroll">{cursor && <Button loading={historyLoading} className="load-earlier" icon={<DownOutlined rotate={180} />} onClick={() => void loadHistory(true)}>加载更早内容</Button>}{historyLoading && turns.length === 0 ? <Spin /> : <Transcript turns={turns} live={live} />}</div><footer className="composer-wrap"><div className="composer"><Input.TextArea aria-label="给 Codex 发送指令" value={prompt} onChange={(event) => setPrompt(event.target.value)} autoSize={{ minRows: 2, maxRows: 8 }} placeholder={selected ? '给 Codex 发送指令…' : '请先选择会话'} disabled={!selected} onPressEnter={(event) => { if (!event.shiftKey) { event.preventDefault(); void send() } }} /><div className="composer-actions"><Space><Button type="text" icon={<ClockCircleOutlined />} disabled={!selected} onClick={() => setScheduling(true)}>定时发送</Button>{selected?.state === 'running' && <Button danger type="text" icon={<StopOutlined />} onClick={() => void interruptSession(csrf, selected.session_id).then(loadSessions)}>中断</Button>}</Space><Button shape="circle" type="primary" icon={<SendOutlined />} loading={sending} disabled={!selected || !prompt.trim()} onClick={() => void send()} aria-label="发送指令" /></div></div></footer></section>

    <Modal title="创建 Codex 会话" open={creating} onCancel={() => setCreating(false)} footer={null}><Form layout="vertical" onFinish={(values: { project: string; mode: 'inspect' | 'edit' }) => { const project = projects.find((item) => item.suggested_project_id === values.project); if (!project) return; void createSession(csrf, project.agent_id, values.project, values.mode).then(() => { setCreating(false); void loadSessions() }).catch((reason: unknown) => setError(reason instanceof Error ? reason.message : '创建失败')) }}><Form.Item label="项目" name="project" rules={[{ required: true }]}><Select options={projects.filter((item) => item.state === 'approved').map((item) => ({ value: item.suggested_project_id, label: `${item.display_name} · ${item.agent_id}` }))} /></Form.Item><Form.Item label="模式" name="mode" initialValue="inspect"><Radio.Group><Radio value="inspect">Inspect（只读）</Radio><Radio value="edit">Edit（隔离 worktree）</Radio></Radio.Group></Form.Item><Button type="primary" htmlType="submit" block>创建</Button></Form></Modal>
    <Modal title="定时发送" open={scheduling} onCancel={() => setScheduling(false)} footer={null}><Form layout="vertical" initialValues={{ delivery: 'at_time', prompt }} onFinish={(values: { delivery: Delivery; prompt: string; runAt?: string; watchId?: string }) => { if (!selected) return; const trigger = values.delivery === 'at_time' ? { type: 'at_time' as const, run_at_unix: Math.floor(new Date(values.runAt!).getTime() / 1000) } : { type: 'experiment_succeeded' as const, watch_id: values.watchId! }; void createSchedule(csrf, selected.session_id, values.prompt, trigger).then(() => { setScheduling(false); setPrompt(''); void fetchSchedules(selected.session_id).then(setSchedules) }).catch((reason: unknown) => setError(reason instanceof Error ? reason.message : '创建定时任务失败')) }}><Form.Item name="delivery" label="触发方式"><Segmented block options={[{ label: '指定时间', value: 'at_time' }, { label: '训练成功后', value: 'experiment_succeeded' }]} /></Form.Item><Form.Item noStyle shouldUpdate>{({ getFieldValue }) => getFieldValue('delivery') === 'at_time' ? <Form.Item name="runAt" label="发送时间（本地时区）" rules={[{ required: true }]}><Input type="datetime-local" /></Form.Item> : <Form.Item name="watchId" label="训练任务" rules={[{ required: true }]}><Select options={experiments.filter((item) => item.state === 'watching' && item.agent_id === selected?.agent_id && item.project_id === selected?.project_id).map((item) => ({ value: item.watch_id, label: item.name }))} /></Form.Item>}</Form.Item><Form.Item name="prompt" label="指令" rules={[{ required: true }, { max: 32768 }]}><Input.TextArea autoSize={{ minRows: 4, maxRows: 10 }} /></Form.Item><Button type="primary" htmlType="submit" block>创建定时任务</Button></Form></Modal>
    <Drawer title="定时任务" open={scheduleListOpen} onClose={() => setScheduleListOpen(false)}><List locale={{ emptyText: '当前会话没有定时任务' }} dataSource={schedules} renderItem={(item) => <List.Item actions={['pending', 'queued'].includes(item.state) ? [<Button key="cancel" danger type="link" onClick={() => void cancelSchedule(csrf, item.schedule_id).then(() => { if (selectedId) return fetchSchedules(selectedId).then(setSchedules) })}>取消</Button>] : undefined}><List.Item.Meta title={item.trigger.type === 'at_time' ? new Date(item.trigger.run_at_unix * 1000).toLocaleString() : '训练成功后'} description={<Space><Tag>{item.state}</Tag><Typography.Text type="secondary">{item.trigger.type === 'experiment_succeeded' ? item.trigger.watch_id : item.schedule_id}</Typography.Text></Space>} /></List.Item>} /></Drawer>
  </main>
}
